Bundle[WIP]
ArtFXDev/silex_client pull request #413
Opened 2022-03-24 15:59 UTC by GuillaumeRoeder

2022-04-08 11:20 UTC, Acedyn requested changes

2022-04-08 11:20 UTC, Acedyn commented on silex_client/commands/copy.py
> +                    Exception(f"Fail to copy {src_path} to {dst_path}")
forget raise

2022-04-08 11:20 UTC, Acedyn commented on silex_client/commands/build_bundle_path.py
> +            "value": 1,
true

2022-04-08 11:20 UTC, Acedyn commented on silex_client/commands/expand_paths.py
> +        return {"expanded_paths": expanded_paths , 'envs': environement_var}
environment

2022-04-08 11:20 UTC, Acedyn commented on silex_client/commands/set_env.py
> +    Replace path by environement variables if it exists
environment

2022-04-08 11:20 UTC, Acedyn commented on silex_client/commands/rename.py
> +from silex_client.utils import files
check if  impoorted

2022-04-08 11:20 UTC, Acedyn commented on silex_client/commands/select_bundle.py
> +class SelectBundle(CommandBase):
checker heritage

2022-04-08 11:20 UTC, Acedyn commented on silex_client/commands/select_bundle_reference.py
> +class SelectBundleReference(CommandBase):
checker heritage

2022-04-08 11:20 UTC, Acedyn commented on silex_client/utils/constants.py
> +# Match environement variable in path for differente format
environment
different

2022-04-08 11:20 UTC, Acedyn commented on silex_client/utils/files.py
> +def reload_recursive(parent_module: ModuleType) -> None:
delete, no use anymore

2022-04-11 15:25 UTC, johhnry approved these changes
LGTM

2022-04-11 15:27 UTC, Acedyn approved these changes

2022-04-11 15:27 UTC, merged